//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travels.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelsDBEntities : DbContext
    {
        public TravelsDBEntities()
            : base("name=TravelsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Travel> Travel { get; set; }
        public virtual DbSet<TravelPlaces> TravelPlaces { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
