//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travels.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelPlaces
    {
        internal int id_user;
        internal int id_category;
        internal int id_cityname;

        public int IdTravelPlaces { get; set; }
        public int id_travel { get; set; }
        public int id_place { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Travel Travel { get; set; }
        public virtual Users Users { get; set; }
    }
}
